### ISSUE TITLE
Guidelines for compiling own darknet file using your repo

### ISSUE THREAD

**Issue by norahsakal** [fmacrae/YOLO-on-Lambda#1]
What a great repo, really helped me a lot with deploying Lambda with Darknet, huge thanks for sharing! 

I had to make some changes to some files, mainly **parse.c** and **image.c**  to be able to printf the coordinates of the bounding boxes after prediction (I added **printf("Bounding Box: Left=%d, Top=%d, Right=%d, Bottom=%d\n", left, top, right, bot);** to  image.c to get the coordinates as an example). 

To be able to change **parse.c** and **image.c** I **cloned https://github.com/pjreddie/darknet**, made my changes and tried to compile my own version with the rest of your weights/settings/repo, but I'm facing numerous errors since certain libraries like **libmvec.se** (I'm getting **"error while loading shared libraries: libmvec.so.1: darknet"** when running my compiled darknet file) seems to be missing.

Would you mind giving pointers or guides of how you compiled/build your darknet file? Or provide the source files of your darknet before compiling/building your final darknet file?
**Huge thank you again for sharing.**

**Comment by fmacrae** [comment]
Sorry for the late reply, I just used the precompiled version pjreddie distributed. Probably best to open the issue with his repo as I'm just a user of his efforts and not actively contributing.
